### ISSUE TITLE
Shouldn't use RegExp for exact matches.

### ISSUE THREAD

**Issue by sradu** [jcoene/mongoid-searchable#1]
We use mongoid-searchable with exact matching. Exact matching generates a regexp query /^search$/.

In our tests this is 400ms slower than using a raw keyword search.

MONGODB test['places'].find({:keywords=>{"$all"=>["bluedrive"]}, :latlng=>#<BSON::OrderedHash:0x1fb1ebc {"$near"=>[40.779956, -73.971441], "$maxDistance"=>1}>})
800ms

MONGODB test['places'].find({:keywords=>{"$all"=>[/^bluedrive$/]}, :latlng=>#<BSON::OrderedHash:0x215c398 {"$near"=>[40.779956, -73.971441], "$maxDistance"=>1
1200ms

Why does mongoid-searchable need regexp for exact searches?

**Comment by jcoene** [comment]
Good catch! Thanks for the contribution.

I've released 0.1.3 which should fix the issue.

**Comment by sradu** [comment]
Thanks.
