### ISSUE TITLE
"search" method name collision

### ISSUE THREAD

**Issue by jgaldrich** [jcoene/mongoid-searchable#2]
Hey, thanks for the great gem. I was part way through writing my own when I came across yours. I ran into a problem when using it with the mongoid-ancestry gem. I was chaining the search method with ancestry like so:

```
Root.children.search("Foo")
```

This resulted in an invalid BSON::ObjectId "foo" exception. I expected there was a name collison for "search", so I forked the project and renamed the method to "text_search" and it works like a charm now.

**Comment by jcoene** [comment]
I think your change is appropriate - replacing "search" with "text_search" is a probably good idea for long-term compatibility. I've released a new version of the gem (0.2.0) which renames the method and updates specs and documentation accordingly.

Please give it a try and let me know if you encounter any issues.  Thanks!

**Comment by jgaldrich** [comment]
Awesome. Thanks!
